# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
# cache: cocoapods
podfile: Example/Podfile

before_install:
- pod install --project-directory=Example
- gem install cocoapods # Since Travis is not always on latest version

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/XUI.xcworkspace -scheme XUI-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
